apiVersion: v1
kind: Service
metadata:
  name: test-app
  labels:
    app: test-app
    environment: {{ .Values.environment }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ .Values.backendConfig.name }}"}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: test-app
